version: '3'

services:
  redis:
    image: redis:alpine

  mongo:
    image: mongo

  backend:
    build: ./backend
    depends_on:
      - redis
      - mongo
    command: python ./manage.py runserver 0.0.0.0:8000

    environment:
      SECRET_KEY: super-secret-key
      REDIS_URL: redis://redis
      DATABASE_URL: ''
      DEBUG: 'true'

    volumes:
      - ./backend:/app

    ports:
      - 8000:8000
