on: [pull_request]
jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up Python
        uses: actions/setup-python@v1

      - name: Install dependencies
        run: pip install black

      - name: Lint
        run: black --check backend/
