on: [pull_request]

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up Python
        uses: actions/setup-python@v1

      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv install --deploy --system
        working-directory: ./backend

      - name: Run all tests
        run: pytest
        working-directory: ./backend
        env:
          SECRET_KEY: secret_key
          DEBUG: 1
          REDIS_HOST: redis
          DATABASE_URL: ''
          REDIS_PORT: 6379
